<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('List of actions') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('action-tracker/action-tracker-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>


<!-- render a data grid -->
<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'actions-tracker-administration',
    'action' => 'list',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => [
        [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        [
            'title' => $this->translate('Description')
        ],
        [
            'title' => $this->translate('Date'),
            'order_name' => 'registered'
        ],
        [
            'title' => $this->translate('Module')
        ]
    ],
    'paginator' => $this->paginator,
    'skipped_fields' => [
        'description_params'
    ],
    'helpers' => [
        'description' => 'actionTrackerDescription',
        'module' => 'translate',
        'registered' => 'applicationDate'
    ],
    'helpers_options' => [
    ],
    'helpers_set_array' => [
        'description' => true
    ],
    'actions' => [
        'regular_actions' => [
        ],
        'multiple_actions' => [
            [
                'name' => $this->translate('Delete selected'),
                'controller' => 'actions-tracker-administration',
                'action' => 'delete',
                'check_acl' => true,
                'confirm' => $this->translate('Selected actions log will be deleted. Are you sure?')
            ]
        ],
        'single_actions' => [
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'action-tracker-actions-log',
        'multiple_actions' => [
            'items_name' => 'actions[]'
        ]
    ],
    'actions_extra_check' => [
        'single_actions' => [
        ]
    ]
]) ?>

<!-- render a data grid -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Actions'),
    'body' => $this->content
]) ?>