<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'ActionTracker\Module'                                           => __DIR__ . '/Module.php',
    'ActionTracker\Controller\ActionTrackerAdministrationController' => __DIR__ . '/src/ActionTracker/Controller/ActionTrackerAdministrationController.php',
    'ActionTracker\Event\ActionTrackerEvent'                         => __DIR__ . '/src/ActionTracker/Event/ActionTrackerEvent.php',
    'ActionTracker\Form\ActionTrackerFilter'                         => __DIR__ . '/src/ActionTracker/Form/ActionTrackerFilter.php',
    'ActionTracker\Model\ActionTrackerAdministration'                => __DIR__ . '/src/ActionTracker/Model/ActionTrackerAdministration.php',
    'ActionTracker\Model\ActionTrackerBase'                          => __DIR__ . '/src/ActionTracker/Model/ActionTrackerBase.php',
    'ActionTracker\View\Helper\ActionTrackerDescription'             => __DIR__ . '/src/ActionTracker/View/Helper/ActionTrackerDescription.php',
    'ActionTracker\Test\ActionTrackerBootstrap'                      => __DIR__ . '/test/Bootstrap.php',
];
